### PR TITLE
Upgrade Falco to 1.2.0

### PR DESCRIPTION
**Pull request by pimbrouwers**
Apologies for the screw up on this Ryan!

Hopefully this is easy enough to merge in.

### CODE REVIEW

**Comment by panesofglass** [comment]
Thanks, but I think the other update has already been merged. You could redirect this PR to the-benchmarker/web-frameworks if you want to make some of the additional changes, e.g. choosing FSharp.Core 4.7.2.

**Comment by pimbrouwers** [comment]
@marwan are you cool with this?

**Review by panesofglass — COMMENTED** [review]
Let me get my branch refreshed, and I’ll submit it.

**Comment by marwan** [comment]
@pimbrouwers hey, I’m sorry but I’m not sure why I was mentioned here?

**Comment by pimbrouwers** [comment]
Thanks Ryan! Ive got a pending PR in the main project. So once you get
caught up it should be fine without a PR from this branch.

**Pull request merged**
